# À adapter avec tes valeurs (visibles dans SonarCloud > ton projet > Information)
sonar.projectKey=ton-org_ton-projet
sonar.organization=ton-org

sonar.sources=src

sonar.exclusions=node_modules/**,dist/**,build/**